name: Generate Error Codes

on:
  repository_dispatch:
    types:
      - generate-errors
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install TypeScript dependencies
        run: pnpm install

      - name: Generate TypeScript errors
        run: pnpm prepublishOnly

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ github.event.client_payload.commit-message }}
          title: "Uptake new error codes"
          body: ":robot: This PR updates the error codes. Merging this PR will trigger a deployment for the TS domain."
          branch: "update-error-codes"
          team-reviewers: "api-maintainers"